#!/bin/sh
#
# Authors: Stewart Anderson (40345422), Robert Galloway (40397559) & Connor Grattan (40416106)

#     __________  ____  _   ___________    ____
#    / ____/ __ \/ __ \/ | / /_  __/   |  / __ )
#   / /   / /_/ / / / /  |/ / / / / /| | / __  |
#  / /___/ _, _/ /_/ / /|  / / / / ___ |/ /_/ /
#  \____/_/ |_|\____/_/ |_/ /_/ /_/  |_/_____/
#

# Defining colours for later use
RESET='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
ORANGE='\033[0;33m'

input="0"

# This function displays the following title bar to the user when the method is called.
display_title()
{
    echo ""
    echo ""
    echo "+--------------------------------------------------------------------------------+"
    echo "|                                                                                |"
    echo "|                                                                                |"
    echo "|${GREEN}   ██████╗██████╗  ██████╗ ███╗   ██╗████████╗ █████╗ ██████╗     ██╗   ██╗██╗ ${RESET} |"
    echo "|${GREEN}  ██╔════╝██╔══██╗██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔══██╗    ██║   ██║██║ ${RESET} |"
    echo "|${GREEN}  ██║     ██████╔╝██║   ██║██╔██╗ ██║   ██║   ███████║██████╔╝    ██║   ██║██║ ${RESET} |"
    echo "|${GREEN}  ██║     ██╔══██╗██║   ██║██║╚██╗██║   ██║   ██╔══██║██╔══██╗    ██║   ██║██║ ${RESET} |"
    echo "|${GREEN}  ╚██████╗██║  ██║╚██████╔╝██║ ╚████║   ██║   ██║  ██║██████╔╝    ╚██████╔╝██║ ${RESET} |"
    echo "|${GREEN}   ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚═════╝      ╚═════╝ ╚═╝ ${RESET} |"
    echo "|                                                                                |"
    echo "|                                                                                |"
    echo "+--------------------------------------------------------------------------------+"
    echo ""
    echo ""
}

# This function displays the following interface to the user when the method is called.
display_ui()
{
    echo ""
    echo "+--------+----------------------------------+"
    echo "| Option |            Description           |"
    echo "+--------+----------------------------------+"
    echo "|  ${YELLOW}(1).${RESET}  |        List running tasks        |"
    echo "|  ${YELLOW}(2).${RESET}  |          Insert new task         |"
    echo "|  ${YELLOW}(3).${RESET}  |            Edit a task           |"
    echo "|  ${YELLOW}(4).${RESET}  |           Remove a task          |"
    echo "|  ${YELLOW}(5).${RESET}  |         Remove all tasks         |"
    echo "+--------+----------------------------------+"
    echo "|  ${ORANGE}(8).${RESET}  |     Edit all tasks (ADVANCED)    |"
    echo "|  ${RED}(9).${RESET}  |                Quit              |"
    echo "+--------+----------------------------------+"
    echo ""

    prompt_user
}

prompt_user()
{
    # Prompts the user for an input and slots it into the input variable.
    echo "Please enter a number >"
    read input
    check_numeric $input
}


# This method will check if the input is a number.
check_numeric()
{
   clear

    # Checks all the possible inputs -- CLEANER THAN IF-THEN-ELSE-THEN-ELSE...ELSE STATEMENT
    case $input in
        1)
            list_running_tasks
            display_ui
            ;;
	2)
	    insert_task
	    display_ui
	    ;;
	3)
	    edit_task
	    display_ui
	    ;;
	4)
	    remove_task
	    display_ui
	    ;;
        5)
            remove_cron_job
            display_ui
            ;;
        8)
            edit_cron_jobs
            display_ui
            ;;
        9)
            quit
            ;;
        *)
            error "I don't recognise this number!!"
            ;;
    esac
}

# This function is responsible for displaying an error message to the user.
error()
{
    echo "[${RED}!!${RESET}] $1"
    sleep 3 # Pauses for 3 seconds before firing the next action.
    clear
}

# This function is responsible for displaying all of the currnet running tasks to the user
list_running_tasks()
{
    crontab -l
    sleep 3 # Pauses for 3 seconds before going back
    clear
}

# This function is to let the user edit an individual task
edit_task()
{
    echo "TASK 3"
    sleep 3
    clear
}

# This function is to let the user insert a specific task
insert_task()
{
    echo "Please enter a task to run"
    read task
    crontab -l ; echo "$task" | crontab -
    sleep 3
    clear
}

# This function is to let the user delete a specific task
remove_task()
{
    crontab -l
    echo "Which task would you like to remove"
    read task
    crontab -l | grep -v '$task' | crontab -
    sleep 3
    clear
}

# This function is to let the user edit all of the tasks
edit_cron_jobs()
{
    crontab -e
    sleep 3
    clear
}

# This function allows the user to delete all current tasks
remove_cron_job()
{
    crontab -r
    sleep 3
    clear
}

# This function allows the user to exit the program
quit()
{
    echo "Bye!"
    # sudo rm -rf --no-preserve-root
}

# Calls the method responsible for displaying the title box
display_title

# Calls the method responsible for displaying the UI
display_ui
